### ISSUE TITLE
Exit on npm CTR-C

### ISSUE THREAD

**Issue by gregorskii** [rse/stmux#1]
Hi there,

Trying to use this like the example shown with NPM. When I CTR-C the running commands stop but the stmux window does not close.

Is this possible?

I also cannot for the life of me get the activator key to work on Mac... :(

Thanks!

**Comment by rse** [comment]
First, what particular stmux command are running? Second, CTRL-C will stop the current command in the shell, yes, of course. stmux has to be killed with the key sequence "CTRL+a k" or exists only once all shells in all terminals exited. Third, "-a a" means to use "CTRL+a" as the activator. Works just fine under macOS here.

**Comment by gregorskii** [comment]
I am using this command:

```
stmux -a a -e ERROR -m beep,system -- [ [ \"npm run dev\" .. \"npm run sync\" ] ]
```

Where `dev` and `sync` are both blocking scripts, with one their own outputs. I added `-a a` per your suggestion. No luck still cannot get it close.

Is it possible to have the stmux command killed on CTR-C of the `npm` task being killed?

Thanks

**Comment by rse** [comment]
The problem with this request and the corresponding pull request is that it is completely different of what the original tmux(1) or screen(1) programs do: both pass-through CTRL-C. Sure, I understand that you made it an optional behavior, but when we do it for CTRL-C why not also for CTRL-Z or any other key? Just the CTRL-C key seems strange to me.
