### ISSUE TITLE
Add flag to disable all keyboard input to running processes

### ISSUE THREAD

**Issue by benny-medflyt** [rse/stmux#11]
Hi, thanks for this great package.

I am using it to run a bunch of "watch" processes. None of these require any keyboard input. It is confusing to remember that I have to press `Ctrl-A K` in order to quit. Would be nice if `Ctrl-C` would just kill everything.

This request is similar to #1 and #6, but the difference is that it's not a special case for `Ctrl-C`. For example, `Ctrl-Z` would put the entire stmux session in the background.

It would be nice if the "--mouse" option would continue to work, so that I could scroll up individual split terminal buffers.

Thank you

**Comment by rse** [comment]
I do not plan to change the current behaviour. The "CTRL+a k" I want to keep as it is.
