### ISSUE TITLE
Activator key not working on macOS

### ISSUE THREAD

**Issue by chuckcarpenter** [rse/stmux#14]
Tried using the default `CTRL+a` and also passing the `-a a` or other keys, but no activator command works. e.g., `CTRL+a ?` for help doesn't come up. 

On macOS Mojave and tried in both iTerm2 and terminal apps. 

Is there any more info I can provide to debug?

**Comment by t638403** [comment]
Same here, none of the `Ctrl` commands seem to work
```
Distro: Ubuntu 18.04.3 LTS
Node: v8.12.0
```

**Comment by danrspencer** [comment]
Same issue here.
```
Node: v12.12.0
OSX: 10.14.6
```

**Comment by mittnavnermike** [comment]
Same problem here. Using zsh if that matters

```
Node: v13.8.0
OSX: 10.15.3
zsh: 5.7.1
```

**Comment by mittnavnermike** [comment]
If you use VS Code you can do alot with [tasks](https://code.visualstudio.com/docs/editor/tasks). Managed to do everything that I wanted with that. Which was to:
1. Start dev server in first tab
2. Start backend server in second tab
3. Open third empty tab

**Comment by maximilliangeorge** [comment]
I struggled with this, but it's actually a vim style command. You shouldn't press ctrl+a+[command] at the same time – you *first* press ctrl+a, release the keys, *then* you press the command key of your choice.

Hope this helps someone out!
