### ISSUE TITLE
Use stmux as lib instead of standalone tool

### ISSUE THREAD

**Issue by marmotz** [rse/stmux#17]
Hi,

is it possible to use stmux to display multiple terminal (not in full size) and execute commands programmatically ?

**Comment by fatso83** [comment]
It's quite modular, so you can rip out whatever you need from the src.

**Comment by rse** [comment]
I've currently no plan to make STMUX a library. It is written and intended to be a stand-alone CLI tool simular to TMUX which inspired it.
