### ISSUE TITLE
Cannot copy and paste when using `-M`

### ISSUE THREAD

**Issue by alansouzati** [rse/stmux#20]
I cannot seem to be able to copy and paste when using -M option.

If I remove -M I can select things in the terminal, but I cannot scroll through the individual inner terminals.

**Comment by rse** [comment]
That's intentional by the underlying Blessed environment: if mouse is enabled, the mouse events are passed-through to the terminal application. This one then would have to support copy & pasting. I do not see any chance to change this inside STMUX.
