### ISSUE TITLE
Watch tasks results in ERROR showing (even no exit has happened)

### ISSUE THREAD

**Issue by fatso83** [rse/stmux#27]
For some reason, stmux seems to think all watch tasks (long running processes that does not exit), such as `chokidar`, `tsc --watch`, `jest --watch`, results in errors, as can be seen from the screenshot below. This has no functional consequences, but it is annoying, as people think that something has gone wrong, even though it has not.

```
$ cat .stmux-spec
[
-s 1/30 ['./stmux-help.sh' ]
:
-s 1/10 [ 'npm run dev:clinic' .. 'npm run dev:people' ]
:
[ '$(pnpm bin)/tsc --watch' .. 'npm run test -- --watch'  ]
:
[ 'cd code; npx chokidar "*/src/**/*.js*" "*/src/**/*.ts*" -c "npx eslint_d {path}"']
]
```

![image](https://github.com/rse/stmux/assets/618076/a904c8aa-2eff-4801-b2d8-d450b52a978e)

**Comment by philsherry** [comment]
I was just looking into this same thing after wrestling with the error bell ringing every time the logs churned over something with the _word_ error in them, such as below, despite it being WARN level and my setting being `-e ERROR`

```log
16:47:34,083 WARN [org.keycloak.events] (default task-1) 
type-REFRESH_TOKEN_ERROR, realmId=supersecretrealm, 
clientId=secret-id, userId=xxxx-xxxx-xxxx-xxxx, 
ipAddress=172.17.0.1, error=invalid_token, 
grant_type-refresh_token, refresh_token_type=Refresh, 
refresh_token_id=xxxx-xxxx-xxxx-xxxx, client_auth_method=client-secret
```

But you’re getting this happening without even having that to blame, so now I’m wondering which it is. 😅

**Comment by fatso83** [comment]
> But you’re getting this happening without even having that to blame

Au contraire, mon ami! It never crossed my mind that stmux was contextually aware, and once you said that it matches on error, I could see that both panes have the word error in them! Thanks for telling me. This behavior must be possible to disable, no?

The first:
> Found 0 errors

The second:
> Error: no files matching ...

**Comment by fatso83** [comment]
I never realized what this bit in the README meant:

> stmux has a built-time error detection and notification feature,

I see that this matches what we are experiencing.

After that realization, I looked at the source code and found a module dealing with errors and noticed the `parseErrorPatterns` function. This gets its arguments from the command line and you can even see it [documented in the README](https://github.com/rse/stmux#:~:text=%2De%20%3Cregexp%3E%5B%2C...%5D%2C%20%2D%2Derror%20%3Cregexp).
<img width="929" alt="Skjermbilde 2023-08-31 kl  11 51 52" src="https://github.com/rse/stmux/assets/618076/e2bc7a8c-148c-4326-a946-197bae6b4a2d">

So I guess this is not an error after all, but documented behavior. I do not explicitly see a way of _disabling_ it altogether (PR to pass `--no-errors`?), but one could get the same effect by specifying a non-matching regex, I assume 😄 What about `--errors you-cannot-touch-this`?
