### ISSUE TITLE
Rendering and activation issues on windows

### ISSUE THREAD

**Issue by RangerMauve** [rse/stmux#3]
Hi, I'm running windows 10 and the rendering gets messed up whenever anything changes on the screen.

The first weird thing that happens is that when I open two instances of bash side by side, the cursor first appears to be active on the second panel, but as soon as I type anything it enters it on the second panel.

Sometimes this also results in the rendering being messed up where the cursor on the screen is being rendered at an offset from what it is in the terminal (probably related to the border)

When the text in an instance of bash gets to the bottom, it renders over the border and messes up even more.

Secondly, I've been unable to get the activation to work even when changing the activation key.

**Comment by rse** [comment]
I guess these rendering issues depend on what terminal emulator you are using. I'm using ConEmu and there it works just fine. Perhaps is the `cmd.exe` terminal emulator the problem. Try to use a different one to see whether my guess is correct and the terminal emulator is the issue.
