### ISSUE TITLE
Appears to lose reference to all aliases and global npm installed cli tools

### ISSUE THREAD

**Issue by abritinthebay** [rse/stmux#4]
Trying to run functions or aliases I have in my `.bash_profile` or tools I have installed via `npm -g` fails with 
```
command not found
..:: PROGRAM TERMINATED (code: 127) ::..   
```

Clearly this is less than ideal. Is there a way to enable these?

This is on a Mac, in terminal, on High Sierra.

**Comment by rse** [comment]
Well, this is an issue outside of stmux, as it depends how you call your shell. If you set your aliases in `.bash_profile` you have to use `stmux [ "bash --login" ]` as GNU Bash reads `.bash_profile` only as a login shell. If you place your aliases into `.bashrc` they will be available also for `stmux [ bash ]`.
