### ISSUE TITLE
child process lost

### ISSUE THREAD

**Issue by y-nk** [rse/stmux#9]
This probably not _directly_ related to stmux but i think it should be addressed here : 

I want to use stmux along with rollup _with the watch option_ to build my file, and an other terminal along to have my storybook around.

The rollup watch option _seems like_ popin new process everytime there's a new build to do and it seems like not working well with stmux.

basically, when building, the first time, rollup process would build and hang (waiting for a new build), and when i save a file stmux would declared "process terminated" - which makes me think rollup flow is to wait silently and kill itself/restart a new one when necessary.

is there a way, an option to get this working with stmux ?

**Comment by maximilliangeorge** [comment]
This is also an issue with nodemon and vue-cli, and likely other frameworks also. It would be great to get this working!

It seems killing stmux runs post-* scripts so maybe that can be used to clear zombie processes? It doesn't feel super neat though.

**Comment by maximilliangeorge** [comment]
Related: #18

**Comment by maximilliangeorge** [comment]
I'm going to get bashed for this, but this postscript will kill any processes still running within the current directory. Presuming you started the script using `npm run dev`...

"postdev": "ps aux | grep -i $(pwd) | grep -v grep | awk {'print $2'} | xargs kill -9"

**Comment by maximilliangeorge** [comment]
Here's a hacky solution for anyone out there who wants to quit zombie processes when killing `stmux` with ctrl+a+k. Please note that this will kill *all* processes running from the current directory.

In package.json:

```
"scripts": {
    "frontend": "...",
    "backend": "...",
    "dev": "stmux -w always -- [ \"npm run frontend\" : \"npm run backend\" ]",
    "postdev": "ps aux | grep -i $(pwd) | grep -v grep | awk {'print $2'} | xargs kill -9"
}
```

**Comment by rse** [comment]
On "CTRL+a k" the childs should be now terminated properly.
